services:
  traefik:
    command:
      # Enable secure API and dashboard
      - "--api.dashboard=true"
      - "--api.insecure=${DASHBOARD_INSECURE:-false}"

      # HTTP and HTTPS entrypoint configuration
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Enable Traefik to detect Docker containers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # Automatic HTTP to HTTPS redirection
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # Let's Encrypt configuration (automatic SSL)
      - "certificatesresolvers.le.acme.httpchallenge=true"
      - "certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"

    ports:
      - "443:443"

    labels:
      - "traefik.http.routers.traefik.entrypoints=websecure"
